name: Build & Release EXE

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller `
            --onefile `
            --windowed `
            --name R6 `
            --icon "img/icon.ico" `
            --add-data "img/icon.ico;img" `
            --add-binary "ffmpeg/ffmpeg.exe;ffmpeg" `
            main.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "R6 ${{ github.ref_name }}"
          files: dist/R6.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}